apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: velero
data:
  AZURE_SUBSCRIPTION_ID: {{.Values.azure.subscriptionId}}
  AZURE_TENANT_ID: {{.Values.azure.tenantId}}
  AZURE_CLIENT_ID:  {{.Values.azure.clientId}}
  AZURE_CLIENT_SECRET: {{.Values.azure.clientSecret}}
  AZURE_RESOURCE_GROUP: {{.Values.azure.resourceGroup}}
