apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: velero
type: Opaque
data:
  AZURE_SUBSCRIPTION_ID: {{.Values.azure.subscriptionId | b64enc | quote }}
  AZURE_TENANT_ID: {{.Values.azure.tenantId | b64enc | quote }}
  AZURE_CLIENT_ID:  {{.Values.azure.clientId | b64enc | quote }}
  AZURE_CLIENT_SECRET: {{.Values.azure.clientSecret | b64enc | quote }}
  AZURE_RESOURCE_GROUP: {{.Values.azure.clusterResourceGroup| b64enc | quote }}
